
#application.yml
server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbtest?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: testId
    password: test
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  thymeleaf:
    enabled: true
    prefix=classpath: /template/
    suffix: .html
    encoding: UTF-8
    mvc:
      static-path-pattern: /static/** # korean ? ???
    # todo cache: true ????
    cache: false
    check-template-location: true
  devtools:
    livereload:
      #?????????
      enabled: true
    remote:
      restart:
        #???? ?????
        enabled: true
  spring:
    data:
      redis:
        host: ??? ??
        port: 6370
        url: jdbc:redis://????:????@??? ??:????
        password: ????
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
